- name: nginx install and run
  hosts: nodes
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present
    # - name: start nginx
    #   ansible.builtin.service:
    #     name: nginx
    #     state: started
    #     enabled: yes
    - name: stop nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
