- name: nginx install and run
  hosts: nodes
  become: yes
  tasks:
    - name: install nginx package
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: start nginx
      ansible.builtin.systemd_service:
        name: nginx
        state: started
        enabled: yes
