- name: nginx service
  hosts: localhost
  connection: local
  tasks:
    - name: nginx service needs to be install
      ansible.builtin.dnf:
        name: nginx
        state: latest
    - name: install service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    - name: Remove file (delete file)
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent

  #  - name: install service
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enabled: yes
