- name: nginx service needs to be installed and run
  hosts: Nodes
  become: yes
  tasks:
    - name: nginx service needs to be installed and run
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - mysql-server
        - nginx
        - zip
    - name: nginx service needs to start
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - mysqld
        - nginx
    - name: services needs to be stop
      ansible.builtin.service:
        name: "{{ item }}"
        state: stopped
      loop:
        - mysqld
        - nginx
