- name: nginx service needs to be installed and run
  hosts: Nodes
  become: yes
  tasks:
  - name: nginx service needs to be installed and run
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: Ensure nginx service is running and enabled at boot
    ansible.builtin.systemd_service:
      name: nginx
      state: started
      enabled: yes

    