- name: nginx service 
  hosts: localhost
  connection: local
  tasks:
  - name: nginx service needs to be install
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - nginx
    - mysql-server
    - dnf
  - name: install service
    ansible.builtin.service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - nginx
    - mysqld
    
      
